"""Localized labels for report rendering. Add a language by adding one entry to each dict."""

LABELS: dict[str, dict[str, str]] = {
    "en": {
        "title": "AI Second-Opinion Report",
        "modality": "Image type",
        "question": "Question",
        "answer": "Answer to the question",
        "summary": "Overall impression",
        "findings": "Findings",
        "location": "Location",
        "severity": "Severity",
        "confidence": "Confidence",
        "differential": "Differential diagnosis",
        "recommendations": "Recommendations",
        "limitations": "Limitations",
        "overall_confidence": "Overall confidence",
        "review_banner": "HUMAN REVIEW REQUIRED",
        "no_findings": "No findings reported.",
        "no_analysis": "No automated analysis is available for this study.",
        "disclaimer": (
            "This report was generated by an AI system to support, not replace, clinical judgement. "
            "All findings must be verified by a qualified physician before any clinical decision."
        ),
    },
    "fa": {
        "title": "گزارش نظر دوم هوش مصنوعی",
        "modality": "نوع تصویر",
        "question": "پرسش",
        "answer": "پاسخ به پرسش",
        "summary": "برداشت کلی",
        "findings": "یافته‌ها",
        "location": "محل",
        "severity": "شدت",
        "confidence": "سطح اطمینان",
        "differential": "تشخیص‌های افتراقی",
        "recommendations": "توصیه‌ها",
        "limitations": "محدودیت‌ها",
        "overall_confidence": "سطح اطمینان کلی",
        "review_banner": "نیاز به بررسی انسانی",
        "no_findings": "یافته‌ای گزارش نشد.",
        "no_analysis": "تحلیل خودکاری برای این مطالعه در دسترس نیست.",
        "disclaimer": (
            "این گزارش توسط سامانه‌ی هوش مصنوعی و صرفاً برای پشتیبانی از قضاوت بالینی تهیه شده و جایگزین آن نیست. "
            "تمام یافته‌ها باید پیش از هرگونه تصمیم بالینی توسط پزشک متخصص تأیید شوند."
        ),
    },
}

LANGUAGE_NAMES = {"en": "English", "fa": "Persian (Farsi)"}

SEVERITY: dict[str, dict[str, str]] = {
    "en": {"mild": "mild", "moderate": "moderate", "severe": "severe"},
    "fa": {"mild": "خفیف", "moderate": "متوسط", "severe": "شدید"},
}

CONFIDENCE_LEVEL: dict[str, dict[str, str]] = {
    "en": {"high": "high", "moderate": "moderate", "low": "low", "unknown": "unknown"},
    "fa": {"high": "بالا", "moderate": "متوسط", "low": "پایین", "unknown": "نامشخص"},
}

REVIEW_REASONS: dict[str, dict[str, str]] = {
    "en": {
        "model_unavailable": "The image analysis model did not return a valid result.",
        "low_overall_confidence": "Overall model confidence is below the review threshold.",
        "low_confidence_severe_finding": "A severe finding was reported with low confidence.",
        "no_answer": "The model did not give a clear answer to the question.",
    },
    "fa": {
        "model_unavailable": "مدل تحلیل تصویر پاسخ معتبری برنگرداند.",
        "low_overall_confidence": "سطح اطمینان کلی مدل کمتر از آستانه‌ی بررسی است.",
        "low_confidence_severe_finding": "یک یافته‌ی شدید با سطح اطمینان پایین گزارش شده است.",
        "no_answer": "مدل پاسخ روشنی به پرسش نداد.",
    },
}
